### ISSUE TITLE
Unable to capture button or image in bot response

### ISSUE THREAD

**Issue by DipaliK9** [codeforequity-at/botium-core#110]
Hi,
My bot is based on MS bot framework And I am using FBdirect (Botium-CLI +Testmybot) to automate my bot. But when Bot response consists of image or button, it says undefined. Please help.

**Comment by codeforequity-at** [comment]
The FBDirect mode is based on a library called "facebook-chat-api", which is not officially supported by Facebook (as it just mimics the traffic happening between the Facebook Frontend and Backend).
So the last months it turned out that this is not a good, stable way for testing facebook chatbots.

We are currently working on a Selenium-based connector, which will solve those problems (when ready). 
There are already some samples available here: https://github.com/codeforequity-at/botium-connector-webdriverio

**Comment by codeforequity-at** [comment]
By the way, for MS Botframework, the directline3 connector would be the best option you have.

**Comment by DipaliK9** [comment]
Thanks. But my bot is not using this channel. Is it possible that we can skip the step and execute remaining conversation?

**Comment by DipaliK9** [comment]
As you suggested I set up directline 3 connector for testing purpose. And I am still getting the response undefined with the error message 

`Error: Body-Dry/Line 292: bot response "[object Object]" missing expected property: senderID
    at _.forOwn'

Am I missing anything?

**Comment by DipaliK9** [comment]
There was issue with my convo file. I updated file and it worked for me. It captures image also. 
Thanks for your help.  :)
