### ISSUE TITLE
sed syntax issue

### ISSUE THREAD

**Issue by bindualapati** [codeforequity-at/botium-core#140]
throwing error for "sed -i 10s/.*/\"appId\":\"mymicrosoftappid\",/ simple-prompt-bot.bot" in botiumFluent.js,  the error message is - ERROR:  Error: sed returned error code 1

**Comment by codeforequity-at** [comment]
This command line is for replacing the empty "appId" in one of the Microsoft Bot builder samples with some value (otherwise bot framework will not work).
https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/04.simple-prompt/simple-prompt.bot

Do you have "sed" installed at your workstation ?

**Comment by codeforequity-at** [comment]
Found out that there actually is an error in the sample code. 
In samples/botframework/botium.json, line 15 should refer to the file "simple-prompt.bot", not "simple-prompt-bot.bot" - this has been changed in the Microsoft Bot Builder samples some days ago.
