### ISSUE TITLE
Blank conversation_id with SIMPLEREST_INIT_CONTEXT in convos with more than one message

### ISSUE THREAD

**Issue by staticdev** [codeforequity-at/botium-core#177]
I am using a simplerest with a webservice that needs the user_id/conversation_id. I am using the SIMPLEREST_INIT_CONTEXT. The problem is that, for any convos with more than one message, the conversation_id is getting blank.

My sample botium.json:

```
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "bot-test",
      "CONTAINERMODE": "simplerest",
      "SIMPLEREST_INIT_CONTEXT": "{ \"conversation_id\": \"botium\" }",
      "SIMPLEREST_URL": "http://localhost:5002/reply",
      "SIMPLEREST_METHOD": "POST",
      "SIMPLEREST_HEADERS_TEMPLATE": "{ \"content-type\": \"application/json\" }",
      "SIMPLEREST_BODY_TEMPLATE": "{ \"message\": \"{{msg.messageText}}\", \"user_id\": \"{{context.conversation_id}}\" }",
      "SIMPLEREST_RESPONSE_JSONPATH": "$.reply"
    },
    "Sources": {},
    "Envs": {}
  }
}
```
One convo with error:
```
#me
hi

#bot
hi, how are you?

#me
fine and you?

#bot
i am also fine, thanks for asking
```

When I run botium cli with --verbose I see that the "fine and you?" message is going without conversation_id.

**Comment by codeforequity-at** [comment]
The context is updated after each HTTP Request. If it is not filled with data again, it will be empty. The context represents the "session variables" to track between calls.

You  have 3 options:

1. You can use the [SIMPLEREST_CONTEXT_JSONPATH](https://github.com/codeforequity-at/botium-core/wiki/operation-mode-simplerest#simplerest_context_jsonpath) capability to extract the new context variables (and the conversation id) from each HTTP response.

2. The template view variable "botium.conversationId" is filled for each convo with a GUID value, maybe you can use this in your body template instead of the (not-existing) context variable

3. You are currently using a constant value for the conversationId (in initContext), which is the same for all convos. You can just add this constant value to the body template instead of the context variable

**Comment by staticdev** [comment]
Nice.. I will take the third and easyer approach for now. Thanks a lot.
