### ISSUE TITLE
Dialog flow test with Botium 

### ISSUE THREAD

**Issue by audunni** [codeforequity-at/botium-core#59]
Hi, how can I test dialog flow (watson conversation bot) with Botium-cli when I have context variables? If I set context var value at a parent level I want to verify the dialog flow.

**Comment by codeforequity-at** [comment]
The Botium connector for IBM Watson Connector supports handling of context variables. For each conversation test case, the context will be kept in memory and handed over to IBM Watson.

**Comment by codeforequity-at** [comment]
So, maybe I can help identify the problem, if you still have troubles. When running botium-cli, please add the "-verbose" flag to get more output.

**Comment by audunni** [comment]
Thanks for returning to my question. In my test I am looking to pass/set context variable + value when sending input message during dialogflow test. Is that possible through botium? Watson Ui allows to through "Try it out" quickly manage context variables. I was wondering if I can automate it through botium to verify all different flows? thanks
Let's say:
test#1:
{
  "context": {
    "var1": true
  },

test#2
{
  "context": {
    "var1": false,
    "var2":true
  }

**Comment by codeforequity-at** [comment]
Yes it is possible: instead of comparing the text output in the convo-files, you can as well decide to compare the whole native structure of the dialog output, including the context variables.
If the comparator in the convo-files contains a JSON structure, a partial compare to the native structure is done, instead of simple text matching.

To get you on track with it, please prepare a short test conversation with a user input for which you want to check the context. Enable debug log ("export DEBUG=botium*") and post the output here. I can then help to get the test conversation right.
